# escape=`

# Use the latest Windows Server Core image with .NET Framework 4.8.
FROM buildtools2019-vctools

# Install Chocolatey
RUN powershell [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

RUN powershell choco install python -y --version=3.8.6;
RUN powershell choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y --version=3.19.1; `
    choco install ninja -y --version=1.10.2; `
    choco install git -y --version=2.29.2.3; `
    python -m pip install --upgrade pip; pip install wheel; `
    pip install conan==1.32.0; `
    choco install jfrog-cli -y --version=1.41.2

# Uncomment the lines below for latest versions
#RUN powershell choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y; `
#    choco install ninja -y; `
#    choco install git -y; `
#    python -m pip install --upgrade pip; pip install wheel; `
#    pip install conan; `
#    choco install jfrog-cli -y;


ENTRYPOINT ["C:\\BuildTools\\Common7\\Tools\\VsDevCmd.bat", "-arch=amd64", "&&", "powershell.exe", "-NoLogo", "-ExecutionPolicy", "Bypass"]
